### ISSUE TITLE
homework completed

### ISSUE THREAD

**Issue by hatelove** [DuncanHuang/201603-TDD-Day1-Homework#1]
兩個建議的地方：
1.  $this->assertCount((int) ceil($analysis->getRows() / $rowsGroup), $target);
   這一個 assertion 有含著一點邏輯
2. php 也可以看看有沒有直接驗證 collection 的 assertion package, 會比驗證一個一個 element by index 來得語意清楚。
- 延伸思考，這個 production code 是不是讓使用端可以自己傳入多筆資料，會支援更多使用場景。

**Comment by DuncanHuang** [comment]
@hatelove  感謝91哥，已修改，不知是不是這個意思？

**Comment by hatelove** [comment]
yes, 就是這樣
